#pragma once

// ===========================================================================
// icons — the one place every screen looks up an icon by name, instead of
// referencing a compile-time C identifier directly. Prefers a loaded custom
// pack (icon_pack.h), falling back per-name to the compiled-in default
// (default_icon_table.h) — so a pack that only overrides SOME icons still
// works sanely, and a missing/corrupt/never-downloaded pack silently means
// "use the shipped look," never a crash.
// ===========================================================================

#include <string.h>

#include "default_icon_table.h"
#include "icon_pack.h"

namespace icons {

// Linear search is fine here: looked up once per screen composition (a
// handful of icons per draw), not per pixel, over a table of ~107 entries.
inline const freeink::Icon& get(const char* name) {
  if (const freeink::Icon* fromPack = iconpack::find(name)) return *fromPack;

  for (int i = 0; i < kDefaultIconCount; ++i) {
    if (!strcmp(kDefaultIcons[i].name, name)) return *kDefaultIcons[i].icon;
  }
  // Unknown name (a programming error, not a real runtime condition — every
  // caller passes a literal string matching a table entry) — never return a
  // null reference; the first default icon is a harmless-enough fallback.
  return *kDefaultIcons[0].icon;
}

// Re-parses whatever's currently on SD (called once at boot, and again right
// after a fresh theme download lands — see icon_pack.h::downloadAndLoad()).
inline bool reloadFromPack() { return iconpack::load(); }

}  // namespace icons

// Map a raw Home Assistant weather state (hyphenated, e.g. "clear-night") to
// its hero/forecast-column glyph via icons::get() — unknown/empty falls back
// to "cloudy". Moved here from weather_icons.h (previously generated by
// tools/gen_weather_icons.py) since this is the string-keyed lookup layer a
// runtime theme pack can override through; that file stays pure data.
inline const freeink::Icon& weatherConditionIcon(const char* condition) {
  struct Row { const char* key; const char* name; };
  static const Row kRows[] = {
      {"clear-night", "wx_clear_night"},       {"cloudy", "wx_cloudy"},
      {"exceptional", "wx_exceptional"},       {"fog", "wx_fog"},
      {"hail", "wx_hail"},                     {"lightning", "wx_lightning"},
      {"lightning-rainy", "wx_lightning_rainy"}, {"partlycloudy", "wx_partlycloudy"},
      {"pouring", "wx_pouring"},               {"rainy", "wx_rainy"},
      {"snowy", "wx_snowy"},                   {"snowy-rainy", "wx_snowy_rainy"},
      {"sunny", "wx_sunny"},                   {"windy", "wx_windy"},
      {"windy-variant", "wx_windy_variant"},   {"night-partlycloudy", "wx_night_partlycloudy"},
  };
  if (condition && *condition) {
    for (const Row& r : kRows) {
      if (!strcmp(r.key, condition)) return icons::get(r.name);
    }
  }
  return icons::get("wx_cloudy");
}

inline const freeink::Icon& weatherForecastIcon(const char* condition) {
  struct Row { const char* key; const char* name; };
  static const Row kRows[] = {
      {"clear-night", "wxf_clear_night"},       {"cloudy", "wxf_cloudy"},
      {"exceptional", "wxf_exceptional"},       {"fog", "wxf_fog"},
      {"hail", "wxf_hail"},                     {"lightning", "wxf_lightning"},
      {"lightning-rainy", "wxf_lightning_rainy"}, {"partlycloudy", "wxf_partlycloudy"},
      {"pouring", "wxf_pouring"},               {"rainy", "wxf_rainy"},
      {"snowy", "wxf_snowy"},                   {"snowy-rainy", "wxf_snowy_rainy"},
      {"sunny", "wxf_sunny"},                   {"windy", "wxf_windy"},
      {"windy-variant", "wxf_windy_variant"},   {"night-partlycloudy", "wxf_night_partlycloudy"},
  };
  if (condition && *condition) {
    for (const Row& r : kRows) {
      if (!strcmp(r.key, condition)) return icons::get(r.name);
    }
  }
  return icons::get("wxf_cloudy");
}
