#!/usr/bin/env bash
# Regenerate include/atkinson_font.h — every text face this firmware uses,
# rasterized from Atkinson Hyperlegible (Regular) and merged into one header:
# five proportional ASCII faces (10/12/14/24/28px) plus a digits-only 68px
# anti-aliased face for the big temperature readout.
#
# Requires: Pillow (pip install pillow), the FreeInk SDK checked out next to
# this project (FREEINK_SDK overrides the location), and network access the
# first time (to fetch the TTF from the font's GitHub repo — cached under
# tools/fonts/ after that, so later runs are offline).
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
sdk="${FREEINK_SDK:-$here/../../freeink-sdk}"
gen="$sdk/libs/ui/FreeInkUI/tools/gen_font.py"

fontsdir="$here/fonts"
ttf="$fontsdir/AtkinsonHyperlegible-Regular.ttf"
mkdir -p "$fontsdir"
if [ ! -f "$ttf" ]; then
  echo "fetching Atkinson Hyperlegible..."
  curl -sL -o "$ttf" \
    "https://raw.githubusercontent.com/googlefonts/atkinson-hyperlegible/main/fonts/ttf/AtkinsonHyperlegible-Regular.ttf"
fi

scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT

# Force UTF-8 file I/O in gen_font.py regardless of the host's default locale
# encoding (matters on Windows, where Python defaults to the system codepage
# and would otherwise mangle the em dashes in its own header comment).
export PYTHONUTF8=1

for sz in 10 12 14 24 28; do
  python "$gen" --ttf "$ttf" --size "$sz" --name "AtkinsonHL$sz" --out "$scratch/f$sz.h"
done
python "$gen" --ttf "$ttf" --size 68 --name AtkinsonHLDigits68 \
  --first 0x2D --last 0x39 --alpha --out "$scratch/fdigits.h"

out="$here/../include/atkinson_font.h"
python - "$scratch" "$out" <<'PYEOF'
import re, io, sys

scratch, out_path = sys.argv[1], sys.argv[2]
files = ["f10.h", "f12.h", "f14.h", "f24.h", "f28.h", "fdigits.h"]

bodies = []
for fn in files:
    with io.open(f"{scratch}/{fn}", encoding="utf-8") as f:
        text = f.read()
    m = re.search(r"namespace ui \{\r?\n\r?\n(.*)\r?\n\}  // namespace ui", text, re.S)
    bodies.append(m.group(1))

header = u'''#pragma once

// ===========================================================================
// atkinson_font.h — every text face this firmware uses, in one place.
// AUTO-GENERATED by tools/gen_atkinson_fonts.sh, which drives the FreeInk
// SDK's own tools/gen_font.py (FreeInkUI/tools/gen_font.py) four times plus
// once more for the digit face below — do not edit by hand, regenerate via
// that script instead.
//
// Source: Atkinson Hyperlegible (Regular), designed by the Braille Institute
// of America — https://github.com/googlefonts/atkinson-hyperlegible.
// Licensed under the SIL Open Font License 1.1; embedding rasterized glyph
// bitmaps is permitted.
//
// Five proportional ASCII (U+0020..U+007E) text faces, 1bpp (MSB-first,
// row-major), covering the sizes this app actually needs — see ui.h for
// which Ui::kFontXxx slot binds to which:
//   kAtkinsonHL10Font   10px  — available, not yet bound to a slot (too small
//                               to read on the panel; kept in case something
//                               ever wants it deliberately)
//   kAtkinsonHL12Font   12px  — available under Ui::kFont12, not the small
//                               chrome face anymore (that's 14px now — tested
//                               too small at 12px)
//   kAtkinsonHL14Font   14px  — status-bar / chrome text (Ui::kFontSmall)
//   kAtkinsonHL24Font   24px  — default body text (Ui's unnamed font 0)
//   kAtkinsonHL28Font   28px  — available, not yet bound to a slot
// ...plus a fifth, different-shaped face bundled alongside them: a
// digits-only (U+002D..U+0039: - . / 0-9) anti-aliased 4-bit-coverage face at
// 68px, for the Standby/Climate pages' big temperature readout
// (Ui::kFontTemp) — large hero digits read better anti-aliased than the
// small chrome/body text does, which is why this one differs in both size
// and rendering technique:
//   kAtkinsonHLDigits68Font   68px, digits-only, 4bpp anti-aliased coverage
// ===========================================================================

#include <FreeInkUIFont.h>  // struct FontGlyph / BitmapFont

namespace freeink {
namespace ui {

'''

header += u"\n".join(bodies)
header += u"\n\n}  // namespace ui\n}  // namespace freeink\n"

with io.open(out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(header)

print("wrote", out_path, len(header.encode("utf-8")), "bytes")
PYEOF

echo "done."
